---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: mosquitto
    meta.helm.sh/release-namespace: mosquitto
  name: mosquitto-config
  namespace: mosquitto
data:
  mosquitto.conf: |
    # DO NOT USE IN PRODUCTION
    allow_anonymous true
    # require_certificate: false
    
    # # MQTT with TLS (MQTTS)
    listener 8883
    protocol mqtt

    # # Fetch the generated certificates
    # cafile /etc/ssl/certs/ca-certificates.crt
    # keyfile /mosquitto/certs/tls.key
    # certfile /mosquitto/certs/tls.crt